from __future__ import annotations

from typing import Any, Dict, List


def get_demo_state() -> Dict[str, Any]:
    return {
        "overview": {
            "original_tokens": 48521,
            "compressed_tokens": 10892,
            "tokens_saved": 37629,
            "compression_ratio": 77.6,
            "estimated_cost": 0.081,
            "estimated_cost_saved": 0.047,
            "latency": 184,
            "pipeline_status": "Healthy",
            "quality_score": 0.94,
            "requests": 184,
            "repository_count": 7,
        },
        "pipeline_stages": [
            {"name": "Repository", "status": "done", "detail": "fastapi / agent-runtime"},
            {"name": "Retriever", "status": "active", "detail": "Relevant files ranked"},
            {"name": "Context Ranking", "status": "queued", "detail": "Semantic relevance scoring"},
            {"name": "Paritok Compression", "status": "queued", "detail": "High-density context packing"},
            {"name": "LLM", "status": "queued", "detail": "Model response generation"},
            {"name": "Verification", "status": "queued", "detail": "Tests and guardrails"},
            {"name": "Pull Request", "status": "queued", "detail": "Ready for review"},
        ],
        "token_series": {
            "daily": [
                {"label": "Mon", "original": 8200, "compressed": 1800},
                {"label": "Tue", "original": 9100, "compressed": 1950},
                {"label": "Wed", "original": 9400, "compressed": 2100},
                {"label": "Thu", "original": 10200, "compressed": 2200},
                {"label": "Fri", "original": 10850, "compressed": 2450},
                {"label": "Sat", "original": 11250, "compressed": 2600},
                {"label": "Sun", "original": 11800, "compressed": 2800},
            ],
            "weekly": [
                {"label": "W1", "original": 35800, "compressed": 8860},
                {"label": "W2", "original": 40500, "compressed": 9650},
                {"label": "W3", "original": 47200, "compressed": 10920},
                {"label": "W4", "original": 51800, "compressed": 11850},
            ],
            "monthly": [
                {"label": "Jan", "original": 128000, "compressed": 29200},
                {"label": "Feb", "original": 142000, "compressed": 32500},
                {"label": "Mar", "original": 164000, "compressed": 36900},
                {"label": "Apr", "original": 188000, "compressed": 42100},
            ],
        },
        "compression_timeline": [
            {"label": "09:00", "value": 68},
            {"label": "10:00", "value": 72},
            {"label": "11:00", "value": 75},
            {"label": "12:00", "value": 78},
            {"label": "13:00", "value": 79},
            {"label": "14:00", "value": 77.6},
        ],
        "repositories": [
            {
                "name": "fastapi",
                "files": [
                    {"path": "src/api/routes.py", "status": "selected", "importance": 0.96, "confidence": 0.95, "reason": "Core request handler flow"},
                    {"path": "src/core/security.py", "status": "selected", "importance": 0.91, "confidence": 0.92, "reason": "Auth and middleware context"},
                    {"path": "src/tests/test_routes.py", "status": "removed", "importance": 0.42, "confidence": 0.87, "reason": "Validation coverage redundant"},
                    {"path": "README.md", "status": "removed", "importance": 0.24, "confidence": 0.91, "reason": "Docs duplicate runtime guidance"},
                ],
                "before_context": "The API layer currently logs request metadata inline, producing large repetitive payloads across every handler.",
                "after_context": "The new path centralizes structured logging through a shared middleware and retains only the critical request state.",
            },
            {
                "name": "agent-runtime",
                "files": [
                    {"path": "orchestrator/workflow.py", "status": "selected", "importance": 0.94, "confidence": 0.94, "reason": "Execution orchestration"},
                    {"path": "agents/retriever.py", "status": "selected", "importance": 0.9, "confidence": 0.93, "reason": "Context retrieval pipeline"},
                    {"path": "docs/architecture.md", "status": "removed", "importance": 0.18, "confidence": 0.88, "reason": "Reference docs not needed at runtime"},
                ],
                "before_context": "The runtime has multiple branching steps that duplicate retrieval context for each agent.",
                "after_context": "The workflow now compresses the shared context and preserves only the highest-signal path information.",
            },
        ],
        "analytics": {
            "token_reduction": [50, 58, 63, 71, 77.6],
            "latency": [280, 250, 220, 205, 184],
            "cost": [0.12, 0.1, 0.09, 0.085, 0.081],
            "repository_usage": [29, 41, 52, 63, 71],
            "compression_trend": [66, 69, 72, 75, 77.6],
            "model_usage": ["Claude", "GPT", "Gemini", "Claude"],
            "provider_usage": ["OpenRouter", "Bedrock", "Groq", "OpenRouter"],
            "quality_score": [0.89, 0.91, 0.93, 0.94],
            "request_history": [
                {"label": "08:00", "value": 8},
                {"label": "10:00", "value": 11},
                {"label": "12:00", "value": 14},
                {"label": "14:00", "value": 17},
                {"label": "16:00", "value": 20},
            ],
        },
        "benchmarks": {
            "without_paritok": {
                "tokens": 48210,
                "latency": 292,
                "cost": 0.126,
                "quality": 0.87,
                "execution_time": 7.8,
            },
            "with_paritok": {
                "tokens": 10892,
                "latency": 184,
                "cost": 0.081,
                "quality": 0.94,
                "execution_time": 4.3,
            },
        },
        "history": [
            {
                "id": "run-104",
                "prompt": "Add structured logging across API routes",
                "repository": "fastapi",
                "model": "Claude 4",
                "compression": "77.6%",
                "files_selected": 4,
                "files_removed": 2,
                "quality": "0.94",
                "cost": "$0.081",
                "latency": "184 ms",
                "summary": "Context is compressed around auth and route handling with strong verification coverage.",
            },
            {
                "id": "run-103",
                "prompt": "Reduce retrieval noise in the orchestrator",
                "repository": "agent-runtime",
                "model": "GPT-5",
                "compression": "74.2%",
                "files_selected": 3,
                "files_removed": 2,
                "quality": "0.92",
                "cost": "$0.075",
                "latency": "201 ms",
                "summary": "The workflow resolved retrieval overlap and improved branch consolidation.",
            },
            {
                "id": "run-102",
                "prompt": "Explain the context ranking heuristic",
                "repository": "agent-runtime",
                "model": "Gemini 2.5",
                "compression": "71.1%",
                "files_selected": 2,
                "files_removed": 1,
                "quality": "0.90",
                "cost": "$0.068",
                "latency": "218 ms",
                "summary": "The explanation surfaced the ranking rationale and preserved execution-critical files.",
            },
        ],
    }
